import puppeteer from 'puppeteer';
import { logger } from '../utils/logger';
import { marked } from 'marked';

/**
 * PDF Generation Service
 * Converts markdown content to styled PDF using Puppeteer
 */
class PDFService {
  /**
   * Convert markdown to HTML with styling
   */
  private markdownToHTML(markdown: string, title: string): string {
    const htmlContent = marked.parse(markdown) as string;

    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      line-height: 1.6;
      color: #333;
      padding: 40px;
      max-width: 900px;
      margin: 0 auto;
      background: white;
    }
    
    h1 {
      color: #2c3e50;
      border-bottom: 3px solid #3498db;
      padding-bottom: 10px;
      margin-bottom: 30px;
      font-size: 2.5em;
    }
    
    h2 {
      color: #34495e;
      margin-top: 30px;
      margin-bottom: 15px;
      font-size: 1.8em;
      border-left: 4px solid #3498db;
      padding-left: 15px;
    }
    
    h3 {
      color: #555;
      margin-top: 20px;
      margin-bottom: 10px;
      font-size: 1.4em;
    }
    
    p {
      margin-bottom: 15px;
      text-align: justify;
    }
    
    ul, ol {
      margin-left: 30px;
      margin-bottom: 15px;
    }
    
    li {
      margin-bottom: 8px;
    }
    
    code {
      background-color: #f4f4f4;
      padding: 2px 6px;
      border-radius: 3px;
      font-family: 'Courier New', monospace;
      font-size: 0.9em;
    }
    
    pre {
      background-color: #f4f4f4;
      padding: 15px;
      border-radius: 5px;
      overflow-x: auto;
      margin-bottom: 15px;
      border-left: 3px solid #3498db;
    }
    
    pre code {
      background: none;
      padding: 0;
    }
    
    blockquote {
      border-left: 4px solid #ddd;
      padding-left: 20px;
      margin: 20px 0;
      color: #666;
      font-style: italic;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 20px;
    }
    
    th, td {
      border: 1px solid #ddd;
      padding: 12px;
      text-align: left;
    }
    
    th {
      background-color: #3498db;
      color: white;
      font-weight: bold;
    }
    
    tr:nth-child(even) {
      background-color: #f9f9f9;
    }
    
    strong {
      color: #2c3e50;
    }
    
    em {
      color: #555;
    }
    
    hr {
      border: none;
      border-top: 2px solid #ddd;
      margin: 30px 0;
    }
    
    .header {
      text-align: center;
      margin-bottom: 40px;
      padding-bottom: 20px;
      border-bottom: 2px solid #3498db;
    }
    
    .footer {
      margin-top: 50px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      text-align: center;
      color: #999;
      font-size: 0.9em;
    }
    
    @media print {
      body {
        padding: 20px;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${title}</h1>
    <p style="color: #7f8c8d;">Generated by StudyBuddy AI</p>
  </div>
  
  <div class="content">
    ${htmlContent}
  </div>
  
  <div class="footer">
    <p>Created on ${new Date().toLocaleDateString()} | StudyBuddy Learning Assistant</p>
  </div>
</body>
</html>
    `;
  }

  /**
   * Generate PDF from markdown content
   */
  async generatePDF(markdown: string, title: string): Promise<Buffer> {
    let browser;

    try {
      logger.info('Launching Puppeteer to generate PDF');

      browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
      });

      const page = await browser.newPage();

      // Convert markdown to HTML
      const html = this.markdownToHTML(markdown, title);

      // Set content
      await page.setContent(html, {
        waitUntil: 'networkidle0',
      });

      // Generate PDF
      const pdfBuffer = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: {
          top: '20mm',
          right: '15mm',
          bottom: '20mm',
          left: '15mm',
        },
      });

      logger.info(`PDF generated successfully (${pdfBuffer.length} bytes)`);

      return Buffer.from(pdfBuffer);
    } catch (error: any) {
      logger.error('Error generating PDF:', error);
      throw new Error(`PDF generation failed: ${error.message}`);
    } finally {
      if (browser) {
        await browser.close();
      }
    }
  }

  /**
   * Generate PDF and save to file
   */
  async generatePDFToFile(markdown: string, title: string, outputPath: string): Promise<void> {
    const pdfBuffer = await this.generatePDF(markdown, title);
    const fs = require('fs').promises;
    await fs.writeFile(outputPath, pdfBuffer);
    logger.info(`PDF saved to ${outputPath}`);
  }
}

// Export singleton instance
export const pdfService = new PDFService();
